Fixed compile and runtime errors
Changelog:

Added to installation all project dlls, libs and headers
Audio: Added "OGGSOUND_EXPORT" property definition to CMakeLists.txt

Video:
Fixed Fatal error: ogg/ogg.h: No such file or directory
Fixed Fatal error: vorbis/vorbisfile.h: No such file or directory
Fixed Error: function 'void Ogre::dllStartPlugin()' definition is marked dllimport
Fixed Undefined reference to `vorbis_synthesis'
Made libtheoraplayer being shared because TheoraVideoManager singleton pointer is different in another library instance (changing to shared fixes this)

Demo:
Fixed Fatal error: al.h: No such file or directory
Fixed Missing Windows.h include
Fixed Undefined reference to `vtable for Ogre::OgreVideoPlugin'